### ISSUE TITLE
Checklist for PR (0.1)

### ISSUE THREAD

**Issue by VictorVelarde** [CartoDB/kepler.gl#35]
- [x] Merge pending PR (2)
- [x] Publish toolkit
- [x] Deploy staging --> now
- [x] Validate function from backend 
- [x] After acceptance, ensure all OAuth fixes are in prod
- [x] Tests front (big / small datasets, ...)
- [x] Ask for QA to Prof. Services (1/2 day?) --> not feasible
- [x] Create keplergl-CARTO OAuth app & clientId --> for staging tests
- [x] Create OAuth app in prod for UBER users
- [x] Prepare acceptance environment
    - [x] cdb users created 
    - [x] clean methods? >> script to 'clean user'
    - [x] ensure VPN for testers
- [x] Get acceptance
- [x] Test in PROD (now)
- [x] Create PR upstream
